myfresh/FreshOrder/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$',views.one_order),
    url(r'^commit_order/$',views.commit_order),
    url(r'^user_order/(\d*)$',views.user_order),
    url(r'^FreshCart/$',views.cart_order),
    url(r'^FreshCart/commit_order2/$',views.commit_order2),
    url(r'^FreshCart/user_order/(\d*)$',views.user_order),
]

myfresh/myfresh/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^", include("Adm_Sr_Mod.urls")),
    url(r'^search/', include('haystack.urls')),
    url(r"^FreshOrder/",include("FreshOrder.urls")),
    url(r"^GoodsShow/",include("GoodsShow.urls")),
    url(r"^usermode/",include("usermode.urls")),
    url(r"^usermode/",include("usermode.urls")),
    url(r"^shopping_cart/",include("shopping_cart.urls")),
    url(r'^tinymce/', include('tinymce.urls')),
]

myfresh/FreshOrder/models.py
# encoding=utf-8
from django.db import models
from tinymce.models import HTMLField
class UserInfo(models.Model):
    uname=models.CharField(max_length=20)
    upwd=models.CharField(max_length=50)
    uemail=models.CharField(max_length=40)
    isDelete=models.BooleanField(default=False)

    def __str__(self):
        return self.uname.encode("utf-8");
    class Meta():
        db_table ='UserInfo'

class UserAddress(models.Model):
    user=models.ForeignKey(UserInfo,on_delete=models.CASCADE)
    userName=models.CharField(max_length=20)
    uaddress=models.CharField(max_length=100,null=True,blank=True)
    uphone=models.CharField(max_length=11)
    ucode=models.CharField(max_length=6)
    ustaue=models.BooleanField(default=False)
    def __str__(self):
        return self.userName.encode("utf-8")
    class Meta():
        db_table ='UserAddress'

class TypeInfo(models.Model):
    title=models.CharField(max_length=20)
    isDelete=models.BooleanField(default=False)

    class Meta():
        db_table = 'TypeInfo'
    def __str__(self):
        return self.title.encode("utf-8");


class GoodsInfo(models.Model):
    gtitle=models.CharField(max_length=20)
    gtype=models.ForeignKey(TypeInfo,on_delete=models.CASCADE)
    gprice=models.DecimalField(max_digits=5, decimal_places=2)
    gdesc=models.CharField(max_length=200)
    gdetail=models.CharField(max_length=1000)
    gpic=models.CharField(max_length=200)
    gunit=models.CharField(max_length=8)
    isDelete=models.BooleanField(default=False)
    class Meta():
        db_table = 'GoodsInfo'
    def __str__(self):
        return self.gtitle.encode("utf-8")

    gdesc=HTMLField()
    gdetail=HTMLField()
class CartInfo(models.Model):
    user=models.ForeignKey(UserInfo,on_delete=models.CASCADE)
    goods=models.ForeignKey(GoodsInfo,on_delete=models.CASCADE)
    count=models.IntegerField()
    class Meta():
        db_table = 'CartInfo'
    def __str__(self):
        return self.user



class OrderInfo(models.Model):
    otime=models.DateTimeField(auto_now_add=True)
    user=models.ForeignKey(UserInfo,on_delete=models.CASCADE)
    ototal=models.DecimalField(max_digits=8, decimal_places=2)
    state=models.BooleanField(default=False)
    class Meta():
        db_table = 'OrderInfo'
    def __str__(self):
        return self.user


class OrderDetailInfo(models.Model):
    order=models.ForeignKey(OrderInfo,on_delete=models.CASCADE)
    goods=models.ForeignKey(GoodsInfo,on_delete=models.CASCADE)
    count=models.IntegerField()
    price=models.DecimalField(max_digits=8, decimal_places=2)
    class Meta():
        db_table = 'OrderDetailInfo'
    def __str__(self):
        return self.user
class AreaInfo(models.Model):
    atitle = models.CharField(max_length=20)
    aParent = models.ForeignKey('self',on_delete=models.CASCADE, null=True, blank=True)
    class Meta():
        db_table = 'AreaInfo'

    def __str__(self):
        return self.atitle.encode("utf-8")
class Gcomment(models.Model):
    user=models.ForeignKey(UserInfo,on_delete=models.CASCADE)
    goods=models.ForeignKey(GoodsInfo,on_delete=models.CASCADE)
    gcomment=models.CharField(max_length=2000)
    class Meta():
        db_table = 'Gcomment'
    def __str__(self):
        return self.gcomment
    gcomment=HTMLField()

myfresh/FreshOrder/views.py
#coding=utf-8
from django.shortcuts import render,redirect
from django.core.paginator import Paginator
from .models import *
import json
from django.http import JsonResponse,HttpResponse


#商品详情页面点击"立即购买"即跳转到"提交订单"页面并保存订单信息
def one_order(request):
    gid=request.GET['id']
    gid=int(gid)
    print(type(gid))
    gcount=request.GET['num']
    gcount=int(gcount)
    print(type(gcount))
    username=request.session['uname']
    userid=UserInfo.objects.get(uname=username)
    userid=userid.id
    useradd=UserAddress.objects.filter(user_id=userid,ustaue=1)
    userlist=[]
    for u in useradd:
        userlist.append({'uadd':u.uaddress,'uname':u.userName,'uphone':u.uphone})
    list=GoodsInfo.objects.get(pk=gid)
    totalprice=list.gprice*gcount
    totalsum = totalprice + 10
    listtemp=[]
    listtemp.append({'gpic':list.gpic,'gtitle':list.gtitle,'gprice':list.gprice,'gcount':gcount,'totalprice':totalprice,'totalsum':totalsum})
    context={'pageName':'提交订单','userlist':userlist,'goodslist':listtemp,'gid':gid,'gcount':gcount,'userid':userid,'totalsum':totalsum}

    return render(request, 'FreshOrder/place_order.html',context)



#提交订单更改订单状态
def commit_order(request):
    gid = request.GET['gid']
    gcount=request.GET['gcount']
    userid=request.GET['userid']
    totalsum=request.GET['totalsum']
    uid = UserInfo.objects.get(pk=userid)
    list = GoodsInfo.objects.get(pk=gid)

    orderinfo = OrderInfo()
    orderinfo.ototal=totalsum
    orderinfo.state=True
    orderinfo.user=uid
    orderinfo.save()

    orderdetail = OrderDetailInfo()
    orderdetail.count=gcount
    orderdetail.price=list.gprice
    orderdetail.goods=list
    orderdetail.order=orderinfo
    orderdetail.save()

    return redirect('/FreshOrder/user_order')

#提交订单跳转到用户中心"全部订单页面"
def user_order(request,pindex):
    if pindex=='':
        pindex=1

    username=request.session['uname']
    userid=UserInfo.objects.get(uname=username)
    userid=userid.id
    orderinfo=OrderInfo.objects.filter(user=userid)
    paginator = Paginator(orderinfo, 2)
    page = paginator.page(int(pindex))
    context = {'pageName':'用户中心','page': page}
    return render(request,'FreshOrder/user_center_order.html',context)


#购物车页面点击“结算”按钮跳转至“提交订单”页面并保存订单信息
def cart_order(request):
    print('++++______++++++_____')
    username=request.session['uname']
    userid=UserInfo.objects.get(uname=username)
    userid=userid.id
    useradd=UserAddress.objects.filter(user_id=userid,ustaue=1)
    userlist=[]
    for u in useradd:
        userlist.append({'uadd':u.uaddress,'uname':u.userName,'uphone':u.uphone})
    cartstr=request.GET['cartid']
    print(type(cartstr))
    cartlist=cartstr.split(',')
    print(cartlist)
    cartid=[]
    for str in cartlist:
        cartid.append(int(str))
    print(cartid)
    cartlist=CartInfo.objects.filter(pk__in=cartid)
    total=0
    totalcount=0
    goodslist=[]
    num=0
    for cart in cartlist:
        num+=1
        totalcount += cart.count
        totalprice=cart.goods.gprice*cart.count
        goodslist.append({'num':num,'gpic':cart.goods.gpic,'gtitle':cart.goods.gtitle,'gprice':cart.goods.gprice,'gcount':cart.count,'totalprice':totalprice})
        total+=totalprice

    totalsum=total+10

    context={'pageName':'提交订单','userlist':userlist,'goodslist':goodslist,'totalcount':totalcount,'total':total,'totalsum':totalsum,'cartid':cartid,'userid':userid}

    return render(request,'FreshOrder/place_order_cart.html',context)

#提交购物车页面的订单并之后删除购物车里的商品
def commit_order2(request):

    cartid=request.GET.getlist('cartid')
    cartid=json.loads(cartid[0])
    cartlist=CartInfo.objects.filter(pk__in=cartid)
    totalprice=0
    for n in cartlist:
        totalprice+=n.goods.gprice*n.count

    userid = request.GET['userid']
    uid=UserInfo.objects.get(pk=userid)

    orderinfo=OrderInfo()
    orderinfo.ototal=totalprice
    orderinfo.state=True
    orderinfo.user=uid
    orderinfo.save()


    for m in cartlist:
        orderdetail = OrderDetailInfo()
        orderdetail.count=m.count
        orderdetail.price=m.goods.gprice
        orderdetail.goods=m.goods
        orderdetail.order=orderinfo
        orderdetail.save()
    for c in cartlist:
        c.delete()


    return redirect('/FreshOrder/user_order')

myfresh/templates/FreshOrder/place_order.html
{% extends 'g_base_top_rightsearch.html' %}


{% block right_search_page_center %}


	
	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
            {% for u in userlist %}
			<dd><input type="radio" name="" checked="">{{ u.uadd }}（{{ u.uname }} 收） {{ u.uphone }}</dd>
            {% endfor %}
		</dl>
		<a href="/usermode/user_center_site/" class="edit_site">编辑收货地址</a>

	</div>
	
	<h3 class="common_title">支付方式</h3>	
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" checked>
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>
	
	<div class="common_list_con clearfix" id="pay_list">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>		
		</ul>
        {% for list in goodslist %}
        <ul class="goods_list_td clearfix">
			<li class="col01">1</li>
			<li class="col02"><img src="{{ list.gpic }}"></li>
			<li class="col03">{{ list.gtitle }}</li>
			<li class="col04">500g</li>
			<li class="col05">{{ list.gprice }}元</li>
			<li class="col06">{{ list.gcount }}</li>
			<li class="col07">{{ list.totalprice }}元</li>
		</ul>
        {% endfor %}


	</div>

	<h3 class="common_title">总金额结算</h3>


	<div class="common_list_con clearfix" id="pay_total">


		<div class="settle_con">
            {% for sum in goodslist %}
			<div class="total_goods_count">共<em>{{ sum.gcount }}</em>件商品，总金额<b>{{ sum.totalprice }}元</b></div>
			<div class="transit">运费：<b>10元</b></div>
			<div class="total_pay">实付款：<b>{{ sum.totalsum }}元</b></div>
            {% endfor %}
		</div>

	</div>

	<div class="order_submit clearfix">

        <a href="commit_order/?gid={{ gid }}&gcount={{ gcount }}&userid={{ userid }}&totalsum={{ totalsum }}" id="order_btn">提交订单</a>

	</div>	


	<div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>
		
		<div class="mask"></div>
	</div>

	<script type="text/javascript">


		$('#order_btn').click(function() {

			localStorage.setItem('order_finish',2);

			$('.popup_con').fadeIn('fast', function() {

				setTimeout(function(){
					$('.popup_con').fadeOut('fast',function(){
						window.location.href = 'user_order/';
					});
				},3000)

			});
		});

	</script>

{% endblock right_search_page_center %}

myfresh/templates/FreshOrder/place_order_cart.html
{% extends 'g_base_top_rightsearch.html' %}


{% block right_search_page_center %}


	
	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
            {% for u in userlist %}
			<dd><input type="radio" name="" checked="">{{ u.uadd }}（{{ u.uname }} 收） {{ u.uphone }}</dd>
            {% endfor %}
		</dl>
		<a href="/usermode/user_center_site/" class="edit_site">编辑收货地址</a>

	</div>
	
	<h3 class="common_title">支付方式</h3>	
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" checked>
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>
	
	<div class="common_list_con clearfix" id="pay_list">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>		
		</ul>
        {% for n in goodslist %}
        <ul class="goods_list_td clearfix">

			<li class="col01">{{ n.num }}</li>
			<li class="col02"><img src="{{ n.gpic }}"></li>
			<li class="col03">{{ n.gtitle }}</li>
			<li class="col04">500g</li>
			<li class="col05">{{ n.gprice }}元</li>
			<li class="col06">{{ n.gcount }}</li>
			<li class="col07">{{ n.totalprice }}元</li>

		</ul>
        {% endfor %}

	</div>

	<h3 class="common_title">总金额结算</h3>


	<div class="common_list_con clearfix" id="pay_total">


		<div class="settle_con">
			<div class="total_goods_count">共<em>{{ totalcount }}</em>件商品，总金额<b>{{ total }}元</b></div>
			<div class="transit">运费：<b>10元</b></div>
			<div class="total_pay">实付款：<b>{{ totalsum }}元</b></div>
		</div>

	</div>

	<div class="order_submit clearfix">

        <a href="commit_order2/?cartid={{ cartid }}&userid={{ userid }}" id="order_btn">提交订单</a>

	</div>	


	<div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>
		
		<div class="mask"></div>
	</div>

	<script type="text/javascript">

		$('#order_btn').click(function() {

			localStorage.setItem('order_finish',2);

			$('.popup_con').fadeIn('fast', function() {

				setTimeout(function(){
					$('.popup_con').fadeOut('fast',function(){
						window.location.href = 'user_order/';
					});
				},3000)

			});
		});

	</script>

{% endblock right_search_page_center %}

myfresh/templates/FreshOrder/user_center_order.html
{% extends 'g_base_top_rightsearch.html' %}

{% block right_search_page_center %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/usermode/user_center_info/">· 个人信息</a></li>
				<li><a href="user_center_order.html" class="active">· 全部订单</a></li>
				<li><a href="/usermode/user_center_site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix" id="total_order">
				<h3 class="common_title2">全部订单</h3>
            {% for order in page %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ order.otime }}</li>
					<li class="col02">订单号：{{ order.id }}</li>
                    {% if order.state == 1 %}
					<li class="col02 stress">已支付</li>
                    {% else %}
                    <li class="col02 stress">未支付</li>
                    {% endif %}
				</ul>


				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for list in order.orderdetailinfo_set.all %}
								<ul class="order_goods_list clearfix">
									<li class="col01"><img src="{{ list.goods.gpic }}"></li>
									<li class="col02">{{ list.goods.gtitle }}<em>11.80元/500g</em></li>
									<li class="col03">{{ list.count }}</li>
									<li class="col04">{{ list.price }}元</li>
								</ul>
								{% endfor %}
							</td>
							<td width="15%">{{ order.ototal }}元</td>
                            {% if order.state == 1 %}
                            <td width="15%">已付款</td>
							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
                            {% else %}
							<td width="15%">待付款</td>
							<td width="15%"><a href="#" class="oper_btn">去付款</a></td>
                            {% endif %}
						</tr>
					</tbody>
				</table>
            {% endfor %}


				<div class="pagenation">
                    {% if page.has_previous %}
                        <a href="{{ page.previous_page_number }}">上一页</a>
                    {% endif %}
                    {%for index in page.paginator.page_range  %}
                        {% if index == page.number %}
                         <a href="#">{{ index }}</a>
                        {% else %}

					    <a href="{{ index }}">{{ index }}</a>

                        {% endif %}
                    {% endfor %}
                    {% if page.has_next %}
                        <a href="{{ page.next_page_number }}">下一页></a>
                    {% endif %}]
				</div>


		</div>
	</div>


{% endblock right_search_page_center %}